version: "3"

services:
  db:
    container_name: de_zc_db
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5438:5432"
    networks:
      - de-zc-network

  pgadmin:
    container_name: de_zc_pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - de-zc-network

  data_pipeline:
    container_name: data_pipeline
    build: .
    depends_on:
      - db
    networks:
      - de-zc-network



volumes:
  postgres_data:

networks:
  de-zc-network:
    driver: bridge


